### PR TITLE
Fixed bug in sort algorithm where incorrect assumptions were made on the format of the $key property

### PR DESCRIPTION
**Pull request by hjoelr**
@msaari First off, I wanted to thank you for your extension! It has really helped our site have a much better search experience.

Let me explain this pull request. We have an extension on our site that hooks into the `woocommerce_get_catalog_ordering_args` filter like this:

```php
add_filter( 'woocommerce_get_catalog_ordering_args', 'custom_woocommerce_catalog_ordering_args', 20 );

function custom_woocommerce_catalog_ordering_args( $sort_args ) {
	$orderby_value = isset( $_GET['orderby'] ) ? wc_clean( $_GET['orderby'] ) : apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby' ) );

	if ( 'date' == $orderby_value ) {
		$sort_args['orderby'] = [
			'menu_order' => 'ASC',
			'date'       => 'DESC',
			'title'      => 'DESC',
		];
		$sort_args['order']   = null;
	}

	return $sort_args;
}
```

As you can see, when `date` order is selected, we're changing it to sort by `menu_order`, then `date`, then `title`. This allows us to selectively move items to the front of the results via `menu_order` even if the customer has selected to sort by `date`. This is using a less known feature of the `WP_Query`'s `orderby` field where it can be an array instead of just a string. You can see in the [Wordpress Codex](https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters) that this is possible. If it's an array, then it will order the items based on multiple fields. (If you're interested in the actual code in `WP_Query` that handles this, you can look [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L2152-L2185).)

Ultimately, the `$key` arg of the `relevanssi_object_sort()` function is the `orderby` field in the `WP_Query`.   That means that when `orderby` is an array, the old version of this function would throw an 'Array to string conversion' error any time a sort was done on our site.

So, in order to handle an array of sort fields (ie. multiple levels of fields to sort on), the sorting algorithm needed a rewrite. This pull request is that algorithm rewritten. Here are some things about this new sort function.

- It's backward compatible with the previous one. There shouldn't be any breaking changes.
- It handles sorting multiple levels of keys.
- It works when the key given is in the format like `date ID` where it's supposed to sort by date and then ID.
- It does proper date and number comparison in addition to standard string comparison.

I've tested this updated code on our site and it seems to be working correctly. Please let me know if you have further questions about this or would like to see some tweaks to it. I hope you'll consider merging it into the main project.

### CODE REVIEW

**Comment by msaari** [comment]
Hi, thanks for your pull request, but this whole thing is already rewritten for Relevanssi version 4.0. So this is already fixed, I'm just developing it on the Relevanssi Premium codebase so it doesn't show up here.

But I'll look at your code and see if it's better than what I currently have in some respect.

**Comment by hjoelr** [comment]
@msaari Okay, great. Feel free to use all or part of this in version 4 if it would help. Do you have any idea when version 4 will be coming out?

**Comment by msaari** [comment]
I went through your code, and I noticed you used different comparison methods for different types of data. That wasn't included in my code, so I took that.

Version 4 is coming in this year, but looks like I have enough improvements to release a new version soon.

**Comment by hjoelr** [comment]
@msaari Okay, sounds good. Glad you were able to use some of this. Were you thinking the improved sort would be included in the interim version between now and v4? I'm just trying to get a sense on how long we'll have to keep using our custom fork to keep our multi-level sorting working without error.

**Comment by msaari** [comment]
@hjoelr It's already out today in 3.6.2.

**Comment by hjoelr** [comment]
@msaari Okay, thanks. I just downloaded it to test out. Unfortunately there seems to be a different bug in the sorting algorithm now. Here's a screenshot of the error output:

image

The error on line 187 seems to repeat for every object in the results. Should I submit this in a separate issue?

**Comment by msaari** [comment]
No need, a fixed version is already out now.

**Comment by hjoelr** [comment]
@msaari Okay, great. I downloaded the update and the error has gone away. Thanks for the quick fix!

I'm just curious...do you have a specific reason why you're not using the built-in PHP `usort()` function? I think it is more efficient in both CPU and memory than doing it all directly in PHP and might be easier for other devs to understand how the sort works since it's a standard way of doing sort.

**Comment by msaari** [comment]
No particular reason, this code is originally written by someone else, so I've just taken that and gone with it.

**Pull request closed without merging**
